name: Build & Publish

on:
  push:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  docker-hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    concurrency:
      group: docker-deployment
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set build number
        id: buildnumber
        run: sed -i 's/.9999/.${{github.run_number}}/' ./StammPhoenix.Web/StammPhoenix.Web.csproj

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nicowelles/stammphoenix
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=stable,enable=${{startsWith(github.ref, 'refs/tags/v')}}
          flavor: |
            latest=false

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
