name: Build & Publish

on:
  push:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  docker-hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    concurrency:
      group: docker-deployment
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set build number
        id: buildnumber
        run: sed -i 's/.9999/.${{github.run_number}}/' ./StammPhoenix.Web/StammPhoenix.Web.csproj

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nicowelles/stammphoenix

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  github-packages:
    name: Push to GitHub Packages
    runs-on: ubuntu-latest
    concurrency:
      group: github-deployment
      cancel-in-progress: false
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set build number
        id: buildnumber
        run: sed -i 's/.9999/.${{github.run_number}}/' ./StammPhoenix.Web/StammPhoenix.Web.csproj

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
