name: Build & Publish

on:
  push:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  docker-hub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set build number
        id: buildnumber
        run: |
          $Version = Get-Content .\StammPhoenix.Web\StammPhoenix.Web.csproj | Select-String -Pattern "<Version>([\d.]+)<\/Version>" | % { $($_.Matches.Groups[1]).Value }
          $BuildVersion = $Version.Substring(0, $Version.Length - 2)
          $BuildVersion = $BuildVersion + ".${{github.run_number}}"
          (Get-Content .\StammPhoenix.Web\StammPhoenix.Web.csproj) -replace $Version, $BuildVersion | Set-Content .\StammPhoenix.Web\StammPhoenix.Web.csproj

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nicowelles/stammphoenix

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  github-packages:
    name: Push to GitHub Packages
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set build number
        id: buildnumber
        run: |
          $Version = Get-Content .\StammPhoenix.Web\StammPhoenix.Web.csproj | Select-String -Pattern "<Version>([\d.]+)<\/Version>" | % { $($_.Matches.Groups[1]).Value }
          $BuildVersion = $Version.Substring(0, $Version.Length - 2)
          $BuildVersion = $BuildVersion + ".${{github.run_number}}"
          (Get-Content .\StammPhoenix.Web\StammPhoenix.Web.csproj) -replace $Version, $BuildVersion | Set-Content .\StammPhoenix.Web\StammPhoenix.Web.csproj

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}